### ISSUE TITLE
fetch requests toestaan 

### ISSUE THREAD

**Issue by simonbesters** [rudiedirkx/wappalyzer#14]
Vermoedelijk is wappa om performance-redenen beperkt in requests types. 
React websites van SIM gebruiken fetch om vanuit main.js (geladen vanaf 3rd party / cdn) om alle resources te laden, zie:

https://www.ameland.nl / https://www.achtkarspelen.nl

Door in driver.js naast 'document' en 'script' ook 'fetch' toe te staan zorg je dat de requests niet geblokkeerd worden en zo de verschillende Analytics-tools geladen worden.

driver.js regel 658:

```JS
if (
          (responseReceived && request.isNavigationRequest()) ||
          request.frame() !== page.mainFrame() ||
          !['document', ...(this.options.noScripts ? [] : ['script']), 'fetch'].includes(
            request.resourceType()
          )
        )
```

Op deze manier lukt het wel. Is een tijdelijke oplossing, want misschien moeten we de wappa efficiëntie een stukje terugschroeven om betere resultaten te realiseren.

**Comment by rudiedirkx** [comment]
(Label `invalid` is voor als de maintainer de klacht invalid vindt. Dat is een beetje een Github conventie.)
